/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.rphstudio.procjamitchio.States;

/**
 *
 * @author GRIGNON FAMILY
 */
public class Testimonials
{

    public static final String[] MESSAGE= 
    {
        "Really good. You guys rock! Best. Product. \n Ever!",
        "This burger has got everything I need.     \n I don't know what else to say.",
        "We have no regrets! No matter where you go,\n this burger recipe is the coolest, most  \n happening thing around!",
        "This burger is worth much more than I paid.\n I can't say enough about it.",
        "This burger is the most valuable business  \n resource we have EVER purchased.",
        "I am so pleased with this product. I don't \n always clop, but when I do, it's because \n of this recipe. Not able to tell you how \n happy I am with it.",
        "I love this burger. Absolutely wonderful!",
        "Not able to tell you how happy I am with   \n this burger. I would like to personally  \n thank you for your outstanding product.  \n Just what I was looking for.",
        "Thanks guys, keep up the good work!",
        "The best on the net!",
        "This burger impressed me on multiple levels.",
        "I am completely blown away. It's incredible.\n I'd be lost without this burger .",
        "This burger has completely surpassed my    \n expectations.",
        "I like this burger more and more each day  \n because it makes my life a lot brighter.",
        "I am really satisfied with my burger.",
        "This burger is the next killer food.",
        "This burger should be nominated for burger \n of the year.",
        "If you aren't sure, always go for this     \n burger.",
        "Buy this now.",
        "Nice work on your burger.",
        "I was amazed at the quality of this burger.",
        "It's just amazing.",
        "I'm good to go. ",
        "I couldn't have asked for more than this.",
        "This burger was the best investment I      \n ever made.",
        "This burger saved my life.",
        
    };  

    public static final String[] USER = 
    {
        // boys
        "Noah",
        "Liam",
        "William",
        "Mason",
        "James",
        "Benjamin",
        "Jacob",
        "Michael",
        "Elijah",
        "Ethan",
        "Alexander",
        "Oliver",
        "Daniel",
        "Lucas",
        "Matthew",
        "Aiden",
        "Jackson",
        "Logan",
        "David",
        "Joseph",
        "Samuel",
        "Henry",
        "Owen",
        "Sebastian",
        "Gabriel",
        "Carter",
        "Jayden",
        "John",
        "Luke",
        "Anthony",
        "Isaac",
        "Dylan",
        "Wyatt",
        "Andrew",
        "Joshua",
        "Christopher",
        "Grayson",
        "Jack",
        "Julian",
        "Ryan",
        "Jaxon",
        "Levi",
        "Nathan",
        "Caleb",
        "Hunter",
        "Christian",
        "Isaiah",
        "Thomas",
        "Aaron",
        "Lincoln",
        "Charles",
        "Eli",
        "Landon",
        "Connor",
        "Josiah",
        "Jonathan",
        "Cameron",
        "Jeremiah",
        "Mateo",
        "Adrian",
        "Hudson",
        "Robert",
        "Nicholas",
        "Brayden",
        "Nolan",
        "Easton",
        "Jordan",
        "Colton",
        "Evan",
        "Angel",
        "Asher",
        "Dominic",
        "Austin",
        "Leo",
        "Adam",
        "Jace",
        "Jose",
        "Ian",
        "Cooper",
        "Gavin",
        "Carson",
        "Jaxson",
        "Theodore",
        "Jason",
        "Ezra",
        "Chase",
        "Parker",
        "Xavier",
        "Kevin",
        "Zachary",
        "Tyler",
        "Ayden",
        "Elias",
        "Bryson",
        "Leonard",
        "Greyson",
        "Sawyer",
        "Roman",
        "Brandon",
        "Bentley",
        // girls
        "Emma",
        "Olivia",
        "Sophia",
        "Isabella",
        "Ava",
        "Mia",
        "Emily",
        "Abigail",
        "Madison",
        "Charlotte",
        "Harper",
        "Sofia",
        "Avery",
        "Elizabeth",
        "Amelia",
        "Evelyn",
        "Ella",
        "Chloe",
        "Victoria",
        "Aubrey",
        "Grace",
        "Zoey",
        "Natalie",
        "Addison",
        "Lillian",
        "Brooklyn",
        "Lily",
        "Hannah",
        "Layla",
        "Scarlett",
        "Aria",
        "Zoe",
        "Samantha",
        "Anna",
        "Leah",
        "Audrey",
        "Ariana",
        "Allison",
        "Savannah",
        "Arianna",
        "Camila",
        "Penelope",
        "Gabriella",
        "Claire",
        "Aaliyah",
        "Sadie",
        "Riley",
        "Skylar",
        "Nora",
        "Sarah",
        "Hailey",
        "Kaylee",
        "Paisley",
        "Kennedy",
        "Ellie",
        "Peyton",
        "Annabelle",
        "Caroline",
        "Madelyn",
        "Serenity",
        "Aubree",
        "Lucy",
        "Alexa",
        "Alexis",
        "Nevaeh",
        "Stella",
        "Violet",
        "Genesis",
        "Mackenzie",
        "Bella",
        "Autumn",
        "Mila",
        "Kylie",
        "Maya",
        "Piper",
        "Alyssa",
        "Taylor",
        "Eleanor",
        "Melanie",
        "Naomi",
        "Faith",
        "Eva",
        "Katherine",
        "Lydia",
        "Brianna",
        "Julia",
        "Ashley",
        "Khloe",
        "Madeline",
        "Ruby",
        "Sophie",
        "Alexandra",
        "London",
        "Lauren",
        "Gianna",
        "Isabelle",
        "Alice",
        "Vivian",
        "Hadley",
        "Jasmine",

        
    };
    
    
    
}
